// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv


import "dotenv/config";
import { defineConfig  } from "@prisma/config";

export default defineConfig({
  // Указываем путь к схеме
  schema: "prisma/schema.prisma",
  
  // Настройки для CLI миграций
  migrations: {
    path: "prisma/migrations",
  },
  
  // Переносим подключение к базе данных сюда!
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});